name: CraftConquer2
main: net.anchy.craftconquer.Main
version: 1.0
api-version: 1.16
commands:
  craftconquer:
    description: Description
    usage: /craftconquer
    permission: craftconquer
    aliases: cc